services:
  mysql-transacciones-n:
    image: mysql:8.0
    container_name: mysql-transacciones-n
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: transacciones_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "8081:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./vw_total_amount.sql:/docker-entrypoint-initdb.d/vw_total_amount.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
volumes:
  mysql_data:
